fail_fast: true
repos:
  - repo: local
    hooks:
      - id: cz
        stages: [commit-msg]
        name: Check Commit Message
        entry: cz check --commit-msg-file
        language: system
        pass_filenames: true
        always_run: true

      - id: update-build-files
        stages: [push]
        name: Check build files
        entry: ./pants update-build-files --check
        language: system
        pass_filenames: false
        always_run: true

      - id: tailor
        stages: [push]
        name: Tailor build files
        entry: ./pants tailor --check
        language: system
        pass_filenames: false
        always_run: true

      - id: lint
        stages: [push]
        name: Check lint
        entry: |
          ./pants lint ::
        language: system
        pass_filenames: false
        always_run: true

      - id: check
        stages: [push]
        name: Check static typing
        entry: |
          ./pants check ::
        language: system
        pass_filenames: false
        always_run: true

      - id: test
        stages: [push]
        name: Run tests
        entry: |
          ./pants test --use-coverage ::
        language: system
        pass_filenames: false
        always_run: true
